name: miquido_flutter_lints
description: Collection of Flutter lints that we use and follow in Miquido
version: 0.2.5
homepage: https://www.miquido.com

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.4

dependencies:
  dart_code_metrics: 4.16.0
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
