name: lint_quido
description: Collection of Flutter lints that we use and follow in Miquido
version: 0.3.5
homepage: https://www.miquido.com

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.5"

dependencies:
  dart_code_metrics: ^4.21.2
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
